name = "MiniFastai"
uuid = "d74fb2b4-b9a7-4851-9aa7-1ef1d6fc44e2"
authors = ["Marc Lelarge"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
